services:
  - type: web
    name: youtube-video-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0   # 👈 Force Python 3.10
      - key: EURON_API_KEY
        sync: false
